#!/usr/bin/env python3

import os
import subprocess


def check_kubectl():
    # Check if kubectl is installed
    try:
        subprocess.run(
            ["kubectl", "version"],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except:
        print("kubectl is not installed. Please install it and try again.")
        exit(1)


def check_docker():
    # Check if docker is installed
    try:
        subprocess.run(
            ["docker", "version"],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except:
        print("docker is not installed. Please install it and try again.")
        exit(1)


def main():
    check_kubectl()
    check_docker()

    print("kubectl and docker are installed. Proceeding with deployment...")


if __name__ == "__main__":
    main()
