dataset_params:
  im_channels: 1
  im_size: 256
  name: 'adni'

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.00085
  beta_end : 0.012

ldm_params:
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 128]
  hint_channels: 33
  down_sample : [True, True, True]
  attn_down: [False, False, True]
  time_emb_dim : 64
  norm_channels: 32
  num_heads : 4
  conv_out_channels: 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  condition_config:
    condition_types: ['context']
    context_condition_config:
      attention_levels: [False, False, True]
      context_embed_dim: 8

vae_params:
  z_channels: 4
  down_channels: [64, 128, 256, 256]
  mid_channels: [256, 256]
  down_sample: [True, True, True]
  attn_down: [False, False, False]
  norm_channels: 32
  num_heads: 4
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2

vqvae_params:
  im_channels: 1
  z_channels: 32
  codebook_size : 1024
  down_channels : [32, 64, 128]
  mid_channels : [128, 128]
  down_sample : [True, True]
  attn_down : [False, False]
  norm_channels: 32
  num_heads: 4
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2

train_params:
  seed: 1111
  task_name: 'adni'
  ldm_batch_size: 4
  controlnet_batch_size: 6
  vae_batch_size: 1
  vqvae_batch_size: 1
  disc_step_start: 0
  disc_weight: 0.1
  codebook_weight: 1.0
  commitment_beta: 0.25
  perceptual_weight: 2.0
  kl_weight: 0.0001
  ldm_epochs: 3000
  controlnet_epochs: 3000
  vae_epochs: 20
  vqvae_epochs: 3000
  num_samples : 1
  num_grid_rows : 1
  num_workers: 2
  ldm_lr: 0.000005
  controlnet_lr: 0.000005
  controlnet_lr_steps : [10]
  vae_lr: 0.00003
  vae_acc_steps: 6
  vae_image_save_steps: 256
  save_latents: False
  vae_latent_dir_name: 'vae_latents'
  vqvae_latent_dir_name: 'vqvae_latents'
  ldm_ckpt_name: '/DataRead2/chsong/checkpoints/ldm_checkpoint_12.pth'
  ldm_best_ckpt_name: '/DataRead2/chsong/checkpoints/ldm_best_checkpoint_12.pth'
  vae_autoencoder_ckpt_name: 'vae_autoencoder_ckpt.pth'
  vqvae_autoencoder_ckpt_name: '/DataRead2/chsong/checkpoints/vqvae_autoencoder_ckpt_13.pth'
  vae_discriminator_ckpt_name: 'vae_discriminator_ckpt.pth'
  vqvae_discriminator_ckpt_name: '/DataRead2/chsong/checkpoints/vqvae_discriminator_ckpt_13.pth'
  vqvae_best_ckpt_name: '/DataRead2/chsong/checkpoints/vqvae_best_checkpoint_2.pth'
  controlnet_ckpt_name: '/DataRead2/chsong/checkpoints/controlnet_ckpt_2.pth'
  controlnet_best_ckpt_name: '/DataRead2/chsong/checkpoints/controlnet_best_ckpt_2.pth'
  dataset_csv: '/home/chsong/project/longitudinal/utils/dataset.csv'
  cache_dir: '/DataRead2/chsong/cache'
  cache_dir_B: '/DataRead2/chsong/cache_B'
  cache_dir_sampling: '/DataRead2/chsong/cache_samplig'
  meta_csv: '/home/chsong/project/longitudinal/adni/meta'
  A_csv: '/home/chsong/project/longitudinal/adni/meta/A.csv'
  B_csv: '/home/chsong/project/longitudinal/adni/meta/B.csv'
  evaluate_controlnet_result_name: '/home/chsong/project/longitudinal/adni/samples/evaluate_controlnet_result'
  evaluate_ldm_result_name: '/home/chsong/project/longitudinal/adni/samples/evaluate_ldm_result'
  scale_factor: 1.963382601737976